data = [
    {"frase": "Estoy triste", "estado_animo": "tristeza"},
    {"frase": "Estoy feliz", "estado_animo": "alegria"},
    {"frase": "Me siento solo", "estado_animo": "depresión"},
    {"frase": "No siento apoyo de nadie", "estado_animo": "soledad"},
    {"frase": "Quiero estallar de ira", "estado_animo": "enojado"},
    {"frase": "Me Estoy emocionado", "estado_animo": "alegria"},
    {"frase": "Me siento melancólico", "estado_animo": "tristeza"},
    {"frase": "Me duele la cabeza", "estado_animo": "tristeza"},    
    {"frase": "Me siento vacio", "estado_animo": "depresion"},
    {"frase": "Me siento enojado", "estado_animo": "enojado"},
    {"frase": "Estoy pensativo", "estado_animo": "soledad"},
    {"frase": "Que colera mes das", "estado_animo": "enojado"},
    {"frase": "Nadie me quiere", "estado_animo": "soledad"},
    {"frase": "Estoy solo en esta vida", "estado_animo": "depresion"},
    {"frase": "No me quiero", "estado_animo": "depresion"},
    {"frase": "Es el mejor dia de mi vida", "estado_animo": "alegria"},
    {"frase": "Estoy muy contento de encontrar este foro", "estado_animo": "alegria"},
    {"frase": "Qué buena noticia", "estado_animo": "alegria"},
    {"frase": "Me encanta participar en este foro", "estado_animo": "alegria"},
    {"frase": "Estoy emocionado de aprender cosas nuevas", "estado_animo": "alegria"},
    {"frase": "Este foro me hace sentir joven", "estado_animo": "alegria"},
    {"frase": "Me siento triste por la pérdida de mi amigo", "estado_animo": "tristeza"},
    {"frase": "No estoy muy bien hoy", "estado_animo": "tristeza"},
    {"frase": "Este foro me recuerda a mi juventud", "estado_animo": "tristeza"},
    {"frase": "Me siento solo a veces", "estado_animo": "tristeza"},
    {"frase": "La vida es difícil a veces", "estado_animo": "tristeza"},
    {"frase": "Estoy muy molesto por la política actual", "estado_animo": "enojado"},
    {"frase": "Esto es una injusticia", "estado_animo": "enojado"},
    {"frase": "Me siento impotente para cambiar las cosas", "estado_animo": "enojado"},
    {"frase": "La gente es muy estúpida a veces", "estado_animo": "enojado"},
    {"frase": "El mundo está perdido", "estado_animo": "enojado"},
    {"frase": "Estoy preocupado por mi salud", "estado_animo": "miedo"},
    {"frase": "No sé qué pasará en el futuro", "estado_animo": "miedo"},
    {"frase": "El mundo es un lugar peligroso", "estado_animo": "miedo"},
    {"frase": "Tengo miedo de morir", "estado_animo": "miedo"},
    {"frase": "No sé cómo enfrentarme a la muerte", "estado_animo": "miedo"},
    {"frase": "Estoy muy estresado por mi trabajo", "estado_animo": "ansiedad"},
    {"frase": "No puedo dormir bien", "estado_animo": "ansiedad"},
    {"frase": "Tengo miedo de hablar en público", "estado_animo": "ansiedad"},
    {"frase": "Me siento constantemente preocupado", "estado_animo": "ansiedad"},
    {"frase": "La vida es demasiado abrumadora", "estado_animo": "ansiedad"},
    {"frase": "Hola, ¿cómo puedo ayudarte?", "estado_animo": "neutral"},
    {"frase": "Gracias por tu respuesta", "estado_animo": "neutral"},
    {"frase": "Estoy de acuerdo con tu opinión", "estado_animo": "neutral"},
    {"frase": "Me gustaría saber más sobre este tema", "estado_animo": "neutral"},
    {"frase": "Este foro es muy interesante", "estado_animo": "neutral"},
    {"frase": "Estoy muy contento de encontrar este foro. Es un gran lugar para aprender cosas nuevas y compartir ideas con personas de ideas afines", "estado_animo": "alegria"},
    {"frase": "No estoy muy bien hoy. Mi esposa falleció hace unos meses y me cuesta seguir adelante", "estado_animo": "tristeza"},
    {"frase": "Estoy muy molesto por la política actual. No entiendo cómo la gente puede votar por alguien tan corrupto", "estado_animo": "enojado"},
    {"frase": "Estoy preocupada por mi salud. Me diagnosticaron cáncer hace unos meses y no sé qué pasará", "estado_animo": "miedo"},
    {"frase": "Estoy muy estresado por mi trabajo. Tengo demasiado que hacer y no sé cómo llegar a todo", "estado_animo": "ansiedad"},
    {"frase": "La vida es bella, disfruta cada momento", "estado_animo": "alegria"},
    {"frase": "La juventud pasa, pero la sabiduría perdura", "estado_animo": "alegria"},
    {"frase": "Estoy agradecido por todo lo que tengo en mi vida", "estado_animo": "alegria"},
    {"frase": "La familia es el tesoro más grande que uno puede tener", "estado_animo": "alegria"},
    {"frase": "Cada día que amanece es un regalo", "estado_animo": "alegria"},
    {"frase": "Tengo la suerte de tener una vida plena", "estado_animo": "alegria"},
    {"frase": "Mi familia y amigos son mi mayor riqueza", "estado_animo": "alegria"},
    {"frase": "La jubilación me ha dado tiempo para hacer lo que amor", "estado_animo": "alegria"},
    {"frase": "Recuerdo cuando las cosas eran más simples", "estado_animo": "soledad"},
    {"frase": "Los tiempos han cambiado mucho desde mi juventud", "estado_animo": "soledad"},
    {"frase": "Echo de menos a las personas que ya no están aquí", "estado_animo": "soledad"},
    {"frase": "El mundo era diferente en mis días", "estado_animo": "soledad"},
    {"frase": "Aprender de tus errores es parte de crecer", "estado_animo": "neutral"},
    {"frase": "La paciencia es una virtud que se adquiere con la edad", "estado_animo": "neutral"},
    {"frase": "No te preocupes demasiado por las cosas pequeñas", "estado_animo": "neutral"},
    {"frase": "El tiempo es el mejor maestro", "estado_animo": "neutral"},
    {"frase": "Me preocupo por el futuro de mis nietos", "estado_animo": "ansiedad"},
    {"frase": "Los tiempos son inciertos y me preocupa la economía", "estado_animo": "ansiedad"},
    {"frase": "La salud es frágil, debemos cuidarnos", "estado_animo": "ansiedad"},
    {"frase": "Espero que las cosas mejoren para las generaciones futuras", "estado_animo": "ansiedad"},
    {"frase": "Me siento muy emocionado por mi próximo viaje", "estado_animo": "alegria"},
    {"frase": "Qué día tan hermoso", "estado_animo": "alegria"},
    {"frase": "Estoy muy agradecido por todos los buenos momentos que he tenido en mi vida", "estado_animo": "alegria"},
    {"frase": "Me siento muy feliz de estar vivo", "estado_animo": "alegria"},
    {"frase": "Este foro me hace sentir conectado con el mundo", "estado_animo": "alegria"},
    {"frase": "Me preocupa el futuro de mis hijos", "estado_animo": "miedo"},
    {"frase": "No sé cómo enfrentarme a la muerte", "estado_animo": "miedo"},
    {"frase": "El mundo es un lugar peligroso", "estado_animo": "miedo"},
    {"frase": "Tengo miedo de lo que pueda pasar", "estado_animo": "miedo"},
    {"frase": "Me siento vulnerable", "estado_animo": "miedo"},
    {"frase": "Echo de menos a mis seres queridos que ya no están", "estado_animo": "tristeza"},
    {"frase": "A veces me siento solo y aislado", "estado_animo": "tristeza"},
    {"frase": "La vida no es justa a veces", "estado_animo": "tristeza"},
    {"frase": "Me siento perdido y sin rumbo", "estado_animo": "tristeza"},
    {"frase": "No sé qué hacer con mi vida", "estado_animo": "tristeza"},
    {"frase": "Estoy muy decepcionado con el gobierno", "estado_animo": "enojado"},
    {"frase": "La gente es muy egoísta a veces", "estado_animo": "enojado"},
    {"frase": "Me siento impotente para cambiar las cosas", "estado_animo": "enojado"},
    {"frase": "El mundo es un lugar injusto", "estado_animo": "enojado"},
    {"frase": "No sé cómo lidiar con mi enojo", "estado_animo": "enojado"},
    {"frase": "Estoy muy estresado por mi salud", "estado_animo": "ansiedad"},
    {"frase": "No puedo dormir bien", "estado_animo": "ansiedad"},
    {"frase": "Me siento constantemente preocupado", "estado_animo": "ansiedad"},
    {"frase": "La vida es demasiado abrumadora", "estado_animo": "ansiedad"},
    {"frase": "No sé cómo controlar mi ansiedad", "estado_animo": "ansiedad"},
    {"frase": "Hola, ¿qué hay de nuevo?", "estado_animo": "neutral"},
    {"frase": "Gracias por la información", "estado_animo": "neutral"},
    {"frase": "Estoy interesado en este tema", "estado_animo": "neutral"},
    {"frase": "Me gustaría compartir mi opinión", "estado_animo": "neutral"},
    {"frase": "Este foro es un buen lugar para aprender cosas nuevas", "estado_animo": "neutral"},
]
